server:
  port: 30081
spring:
  application:
    name: good-service
  elasticsearch:
    rest:
      uris: http://localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 123123
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true



mybatis:
  type-aliases-package: org.example.store.po
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl