server:
  port: 30080
spring:
  application:
    name: User-Service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverZone=Asia/Shanghai
    username: root
    password: 123123
  jpa:
    show-sql: true
  redis: # redis的配置
    database: 1
    host: localhost
    port: 6379
    timeout: 10000
  # 配置邮件发送信息
  mail:
    host: smtp.qq.com
    username: 2412601628@qq.com
    password: dzusdxfkqtfyeaaf
    from: 2412601628@qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttle:
            enable: true
          ssl:
            enable: true
mybatis:
  type-aliases-package: org.example.store.po
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  configuration:
#    cache-enabled: true
#    map-underscore-to-camel-case: true

eureka:
  instance:
    instance-id: User-Service
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:30001/eureka/
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    org.example.store.mapper: debug

info:
  app:
    id: user-service
    name: black_soul
    email: 2412601628@qq.com
application:
  url: //localhost:30080
  security:
    key: 123456
  upload:
    # 上传文件的访问路径
    url: /static/images/
    # 上传文件的保存路径
    dir: classpath:static/images/